name: DORA Metrics with SQLite

on:
  schedule:
    - cron: "0 12 * * *"   # daily at 2AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}   # needed to push back changes

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DORA script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER: ${{ secrets.OWNER }}
          REPO: ${{ secrets.REPO }}
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        run: |
          python dora_pipeline.py   # this generates/updates dora.sqlite

      - name: Commit and push updated SQLite DB
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dora.json
          git add dora.sqlite
          git commit -m "Update DORA metrics DB [skip ci]" || echo "No changes to commit"
          git push

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: run-script
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npx vite build
      env:
        NODE_ENV: production

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GH_REPO_TOKEN }}
        publish_dir: ./dist/public
